## yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# read more: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

# assignees: []
body:
  - attributes:
      label: Description
    id: description
    type: textarea
    validations:
      required: true
description: a new feature
labels:
  - dev::feat
  - product::arium
  - team::backend
name: feat
# projects: []
# title: ""
