# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
description: A new feature
labels: ["dev::feat", "product::arium", "team::backend"]
name: Feat
title: "[Feat]: <title>"

body:
  - type: textarea
    id: description
    # attributes:
    #   label: Description
    validations:
      required: true
