# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

# assignees:
body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
description: a new feature
labels: ["dev::feat", "product::arium", "team::backend"]
name: feat
# projects:
# title:
