name: Feat
description: A new feature
title: "[Feat]: <title>"
labels: ["dev::feat", "product::arium", "team::backend"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
